### ISSUE TITLE
Calibration of Roughness - Eq. 105

### ISSUE THREAD

**Issue by TorosSenan** [acoustics-code-salford/refmap-psychoacoustics#8]
# Question
Dear Mike, 

First, thank you for this contribution. I had implemented these more than a year ago and got stuck with the roughness, mostly apparent on low-frequency rich audio data. Going through your script made me notice where the difference between yours and mine is. Hence, my first question: 

I see that you calculated the Hilbert transform as follows: abs(Hilbert (pn_lz)), and then downsampled. The equation states: 
abs(pn_lz + 1i.*(Hilbert (pn_lz))); and I had also implemented it the same way. Is the difference due to the way Hilbert transform is calculated in Matlab or related to the mathematical notation vs signal processing terminology/implementation? When I replaced abs(blocksF + 1i.*(Hilbert (blocksF))), with abs(Hilbert (pn_lz)), the issue in my implementation was largely resolved. So my question is mostly curiosity-driven. 

Additionally, I also noticed how you implemented the calibration equation (Eq. 105) for Roughness, which had puzzled me as well before, hence I had returned to ECMA-418-1, 2020 version just because of that. 
In line 575 of acousticHMSRoughness.m, you code as follows: 

     % Section 7.1.7 Equation 105 [E(l_50)]
     El50 = (0.95555 - **0.58449**)*(tanh(1.6407*(Bl50 - 2.5804)) + 1)*0.5 + 0.58449;

while the standard does not subtract the number **0.58449** from 0.95555, it only writes as follows:
     0.95555 *(tanh(1.6407*(Bl50 - 2.5804)) + 1)*0.5 + 0.58449;

And, if subtraction is applied, the values are correct, but if the equation is implemented without the subtraction as in the standard, then the values are wrong. Can you enlighten me on this? What am I missing? An erratum published somewhere? Personal communication with Prof. Sottek maybe?  

Thank you for your efforts once again, this has been bugging me for long time.

**Comment by mlotinga** [comment]
Thanks for your feedback.

In relation to the Hilbert transform, the way it is defined in Matlab is

_X = hilbert(Xr) computes the so-called discrete-time analytic signal X = Xr + i*Xi such that Xi is the Hilbert transform of real vector Xr._

so I took this as a direct reflection of the way it was written in the standard. I understand the confusion though, I think it had me scratching my head for a while!

In relation to equation 105, it is an error in the standard that I believe will be amended in a forthcoming update.

**Comment by TorosSenan** [comment]
Dear Mike,

Thank you for your response.

Further moving along your script, I also noticed two things that I can't
seem to locate in the standard, and I have been curious if they will also
become the subject of the amendment:

1) In lines 417 - 422, you implemented the bias adjustment (Eq. 78), you
subtracted an additional "1" from the first E(theta) of the equation:
biasAdjust = errorCorrection(thetaCorr + mlabIndex - *1*)...
                                 - (errorCorrection(thetaCorr +
mlabIndex)...
                                    - errorCorrection(thetaCorr + mlabIndex
- 1))...
                                    *errorBeta(thetaCorr + mlabIndex - *1*
)...
                                    /(errorBeta(thetaCorr + mlabIndex)...
                                      - errorBeta(thetaCorr + mlabIndex -
1));
which does not exist in the standard.
2) In the final low-pass filtering (hmSRoughLowPass.m (Eq. 109), you
implemented the equation's second part using the previously low-pass
filtered block, while in the equation it is the previous block of
̂R^(𝑙50−1,𝑧):
Line 67: specRoughness = specRoughEstTform;

Lines 75-78 (and 79-82):
if ~isempty(specRoughEstTform(llBlock, riseMask))
        specRoughness(llBlock, riseMask) = specRoughEstTform(llBlock,
riseMask).*(1 - riseExponent(riseMask))...
                                           + *specRoughness*(llBlock - 1,
riseMask).*riseExponent(riseMask);
    end

Best,

T

**Comment by mlotinga** [comment]
Correct, these also require amendment.
